development:
  adapter: postgresql
  database: craigslist-development
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: craigslist-production
  pool: 5
  timeout: 5000
  url: <%=ENV['DATEBASE_URL']%>
